Update Stately Studio and editor terms
statelyai/docs pull request #80
Opened 2023-04-13 15:47 UTC by laurakalbag

This PR replaces:
- `the Stately Studio` with `Stately Studio` as Stately Studio is the name.
- `Stately Studio Editor` with `Stately Studio’s editor` as the editor is not a proper noun.
- `the Editor` with `the editor` for the same reason as above.

2023-04-13 16:33 UTC, kevinmaes requested changes
That's a lot of edits (and a lot of work)!! Suggested some changes and asked a lot of questions for now.

2023-04-13 16:33 UTC, kevinmaes commented on docs/studio.mdx
> +    alt="Stately Studio Team page for the Voyager team, showing Captain Janeway with the owner and admin role, Commander Chakotay with an admin role, Lieutenant Tuvok, Lieutenant Torees, and Lieutena
Sometime we'll figure out whether these team roles are capitalized or not so we can be more consistent (separate task).

2023-04-13 16:33 UTC, kevinmaes commented on docs/studio.mdx
> +    alt="Stately Studio Team page for the Voyager team, showing Captain Janeway with the owner and admin role, Commander Chakotay with an admin role, Lieutenant Tuvok, Lieutenant Torees, and Lieutena
But I think the find/replace wasn't meant to lowercase this `editor`.

2023-04-13 16:33 UTC, kevinmaes commented on docs/teams.mdx
> +| Reassign Admin, editor, and Viewer roles | ✅ Yes | ✅ Yes | 🚫 No  | 🚫 No  |
```suggestion
| Reassign Admin, Editor, and Viewer roles | ✅ Yes | ✅ Yes | 🚫 No  | 🚫 No  |
```

2023-04-13 16:33 UTC, kevinmaes commented on docs/teams.mdx
> +    alt="Stately Studio Team page for the Voyager team, showing Captain Janeway with the owner and admin role, Commander Chakotay with an admin role, Lieutenant Tuvok, Lieutenant Torees, and Lieutena
Should we capitlaize "owner", "admin" and "editor" here for now?

2023-04-13 16:33 UTC, kevinmaes commented on docs/teams.mdx
> +- Give team members Admin, editor, and Viewer roles
```suggestion
- Give team members Admin, Editor, and Viewer roles
```

2023-04-13 16:33 UTC, kevinmaes commented on docs/teams.mdx
> +Any team member with **Admin**, **editor**, or **Viewer** roles can leave a team.
```suggestion
Any team member with **Admin**, **Editor**, or **Viewer** roles can leave a team.
```

2023-04-13 16:33 UTC, kevinmaes commented on docs/tools/visualizer.mdx
> +Stately still supports the Stately Visualizer, but you will find many more advanced features, including the visual [Studio editor](../#studio-editor), teams, and shared projects.
```suggestion
Stately still supports the Stately Visualizer, but you will find many more advanced features in Stately Studio, including the [visual editor](../#studio-editor), teams, and shared projects.
```

Also, when I see "Visual Studio..." I think of Visual Studio IDE or VSCode.

2023-04-13 16:33 UTC, kevinmaes commented on docs/tools/xstate-vscode-extension.mdx
> +Once installed, you can run `XState: Open Visual editor` from the command palette to open any machine at your cursor’s location.
This should probably go back to being "Editor" since it's the older project.

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +Team members can have one of the following roles: [Owner](/#owner-role), [Admin](/#admin-role), [editor](/#editor-role), or [Viewer](/#viewer-role). Team owners or admins assign the role to the new t
```suggestion
Team members can have one of the following roles: [Owner](/#owner-role), [Admin](/#admin-role), [Editor](/#editor-role), or [Viewer](/#viewer-role). Team owners or admins assign the role to the new team member when inviting them to join the team.
```

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +Users with the editor role can:
```suggestion
Users with the Editor role can:
```

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +3. Use the **...** triple dot contextual menu alongside the team member’s name in the **Members** list to choose from the options **Make a Viewer**, **Make an editor**, or **Make an Admin**.
```suggestion
3. Use the **...** triple dot contextual menu alongside the team member’s name in the **Members** list to choose from the options **Make a Viewer**, **Make an Editor**, or **Make an Admin**.
```
Normally, I'd say we should change the button labels themselves to sentence case except that we're semi-committed to capitalizing these roles for now.

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +    alt="Stately Studio Team page for the Voyager team, showing the options for Lieutenant Tuvok as ‘Make a Viewer’, ‘Make an editor,’ and ‘Remove from team.’"
```suggestion
    alt="Stately Studio Team page for the Voyager team, showing the options for Lieutenant Tuvok as ‘Make a Viewer’, ‘Make an Editor,’ and ‘Remove from team.’"
```

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +Only team members with the **Owner**, **Admin**, or **editor** roles can create team projects.
```suggestion
Only team members with the **Owner**, **Admin**, or **Editor** roles can create team projects.
```

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/visualizer.mdx
> +Stately still supports the Stately Visualizer, but you will find many more advanced features, including the visual [Studio editor](../#studio-editor), teams, and shared projects.
Similar to another instance of this about "visual studio" and stuff.

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +The [XState VS Code extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode) enhances the XState development experience by providing VS Code users with autocomplete, t
Maybe "linting, and a visual editor inside VS Code"?

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +Once installed, you can run `XState: Open Visual editor` from the command palette to open any machine at your cursor’s location.
Similar question here.

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +Upon opening an XState machine in the VSCode editor, you may notice a long `@xstate-layout` comment inserted in the code just above the call to `createMachine()`.
Saw instances of "VS Code" vs "VSCode". 

From their website, it looks like the 2 choices are:

1. "Visual Studio Code"
2. "VS Code"

2023-04-13 16:33 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +This layout string is for persisting manual changes you make to the machine’s layout and is automatically updated by the XState Extension whenever layout changes occur. It is not intended to be human
```suggestion
This layout string is for persisting manual changes you make to the machine’s layout and is automatically updated by the XState Extension whenever layout changes occur. It is not intended to be human-readable nor manually edited. When updates to this string are made by the extension, the file is not saved until a manual save is performed. The layout algorithm is able to interpret this string and automatically format the machine's layout whenever it is re-opened in Stately Studio's editor.
```

Or just leave it "the editor". Either way.

2023-04-14 16:18 UTC, laurakalbag commented on versioned_docs/version-5/finite-states.mdx
> +## Stately Studio’s editor: finite states
These are todo headings right now in the v5 docs

2023-04-14 16:59 UTC, davidkpiano commented on versioned_docs/version-5/finite-states.mdx
> +## Stately Studio’s editor: finite states
For the future, maybe these should just say "Stately Studio: ..."?

2023-04-14 17:14 UTC, kevinmaes commented on versioned_docs/version-5/teams.mdx
> +| Capability                               | Owner  | Admin  | editor | Viewer |
```suggestion
| Capability                               | Owner  | Admin  | Editor | Viewer |
```

2023-04-14 17:15 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +The [XState VS Code extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode) enhances the XState development experience by providing VS Code users with autocomplete, t
```suggestion
The [XState VS Code extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode) enhances the XState development experience by providing VS Code users with autocomplete, typegen, linting, and a visual editor inside VS Code.
```

2023-04-14 17:16 UTC, kevinmaes commented on versioned_docs/version-5/xstate-vscode-extension.mdx
> +Upon opening an XState machine in the VS Code editor, you may notice a long `@xstate-layout` comment inserted in the code just above the call to `createMachine()`.
```suggestion
Upon opening an XState machine in VS Code, you may notice a long `@xstate-layout` comment inserted in the code just above the call to `createMachine()`.
```
Nit: Just to make it shorter and less similar to "Stately Studio's _editor_"

2023-04-14 17:17 UTC, kevinmaes requested changes
Just a couple more small fixes and that should be it.

2023-04-18 11:52 UTC, merged